// src/App.tsx
import { Provider } from 'inversify-react';
import { createContainer } from './lib/Container';
import { useEffect } from 'react';
import { addSdkToBody } from './addSdkToBody';
import { MusicPlayer } from './lib/presentation/MusicPlayer';

export function App() {
    useEffect(addSdkToBody, []);

    return (
        <Provider container={createContainer}>
            <MusicPlayer />
        </Provider>
    );
}

// src/App.svelte
<script lang="ts">
    import Router from 'svelte-spa-router';
    import Home from './Home.svelte';
    import Redirect from './Redirect.svelte';
    import { setContainer } from './lib/svelte-inversify';
    import { createContainer } from './lib/Container';

    setContainer(createContainer());

    const routes = {
        '/': Home,
        '*': Redirect,
    };
</script>

<Router {routes} />
